[project]
name = "rusty_tree"
dependencies = ["cffi==1.15.0", "mpi4py==3.1.3", "numpy==1.22.3"]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[tool.maturin]
bindings = "cffi"
compatibility = "linux"