package:
  name: rusty_tree
  version: 1.1.0

source:
  path: ../

requirements:
  build:
    - gcc # [linux]
    - clang

  host:
    - mpich-mpicc
    - hdf5
    - rust
    - python
    - pip
    - maturin
    - cffi >=1.15

  run:
    - mpich-mpicc
    - python
    - hdf5
    - numpy 1.22.2
    - cffi >=1.15

build:
  # SET HDF5_DIR as root of conda build environment for rust dependency to find headers
  script: export HDF5_DIR=$PREFIX && maturin build --release && python -m pip install .