name: Publish To Anaconda

on: push
  # release:
  #   types: [published]

env: 
  HDF5_DIR_MACOS=/usr/local/miniconda/envs/test/
  RUSTFLAGS_MAC="-C link-args=-Wl,-rpath,/usr/local/miniconda/envs/test/include/lib"
  HDF5_DIR_LINUX=/usr/share/miniconda/envs/test/
  RUSTFLAGS_LINUX="-C link-args=-Wl,-rpath,/usr/share/miniconda/envs/test/include/lib"


jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v3

      - name: Install Conda Build
        shell: bash -l {0}
        run: conda install conda-build

      - name: Install Conda Verify
        shell: bash -l {0}
        run: |
          conda install conda-verify

      - name: Set Linux Env Vars
        shell: bash =l {0}
        run: export HDF5_DIR=${{ env.HDF5_DIR_LINUX}} && export RUSTFLAGS=${{ env.RUSTFLAGS_LINUX }}
      
      - name: Set Mac Env Vars
        shell: bash =l {0}
        run: export HDF5_DIR=${{ env.HDF5_DIR_MACOS }} && export RUSTFLAGS=${{ env.RUSTFLAGS_MACOS }}
    
      - name: Build
        shell: bash -l {0}
        working-directory: crates/rusty-tree/
        run: conda build -c conda-forge -c anaconda conda.recipe --py ${{ matrix.python-version }}

      - name: Install Anaconda Client
        shell: bash -l {0}
        run: conda install anaconda-client

      - name: Upload Linux (${{ matrix.python-version }})
        if: runner.os == 'Linux'
        shell: bash -l {0}
        run: anaconda -t ${{ secrets.ANACONDA }} upload --force --user skailasa  /usr/share/miniconda/envs/test/conda-bld/linux-64/rusty_tree-*.tar.bz2

      - name: Upload Mac (${{ matrix.python-version }})
        if: runner.os == 'macOS'
        shell: bash -l {0}
        run: anaconda -t ${{ secrets.ANACONDA }} upload --force --user skailasa  /usr/local/miniconda/envs/test/conda-bld/osx-64/rusty_tree-*.tar.bz2
